<div id="footer">
    <div class="top">
        <div class="container">
            <div class="col-md-6 with-us">
                <h5 class="col-md-5">CONTENT WITH ABOUT</h5>
                <a href="#"><i class="fa fa-facebook"></i></a>
                <a href="#"><i class="fa fa-twitter"></i></a>
                <a href="#"><i class="fa fa-google-plus"></i></a>
                <a href="#"><i class="fa fa-linkedin"></i></a>
                <a href="#"><i class="fa fa-pinterest"></i></a>
            </div>
            <div class="col-md-6 form-inline subscribe-us">
                <h5 class="col-md-5">NEWSLETTER SIGN UP</h5>
                <form class="form-group">
                    <input class="form-control" type="text" value="" placeholder="Enter your email address"/>
                    <button class="btn" type="submit">SUBMIT</button>
                </form>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="container">
            <div class="col-md-3 about">
                <h5>ABOUT THE DAILYDEAL</h5>
                <p>Sollicitudin, lorem quis bibendum auctor,
                    nisi elit consequat ipsum, nec sagittis sem
                    nibh id elit. Duis sed odio sit amet nibh
                    vulputate cursus a sit amet mauris. Morbi
                    accumsan ipsum velit. Nam nec tellus a
                    tincidunt auctor a ornare odio.</p>
            </div>
            <div class="col-md-3 information">
                <h5>INFORMATION</h5>
                <li class=""><a href="#"><i class="fa fa-angle-right"></i>About Us</a></li>
                <li class=""><a href="#"><i class="fa fa-angle-right"></i>Delivery information</a> </li>
                <li class=""><a href="#"><i class="fa fa-angle-right"></i>Privacy Policy</a> </li>
                <li class=""><a href="#"><i class="fa fa-angle-right"></i>Terms & Conditions</a> </li>
                <li class=""><a href="#"><i class="fa fa-angle-right"></i>Contact Us</a> </li>
            </div>
            <div class="col-md-3 contact">
                <h5>CONTACT US</h5>
                <li>
                    <i class="fa fa-map-marker"></i>Address 1 store
                    <address>1 Dai Co Viet</address>
                    <phone>(+84)9781357xxx</phone>
                </li>
                <li>
                    <i class="fa fa-map-marker"></i>Address 1 store
                    <address>1 Dai Co Viet</address>
                    <phone>(+84)9781357xxx</phone>
                </li>
            </div>
            <div class="col-md-3 open-time">
                <h5>OPENING TIME</h5>
                <li>
                    <i class="fa fa-clock-o"></i>Momday-Friday
                    <i class="pull-right">8.00 to 18.00</i>
                </li>
                <li>
                    <i class="fa fa-clock-o"></i>Saturday
                    <i class="pull-right">9.00 to 21.00</i>
                </li>
                <li>
                    <i class="fa fa-clock-o"></i>Sunday
                    <i class="pull-right">10.00 to 21.00</i>
                </li>
            </div>
        </div>
    </div>
    <div class="bottom">
        <div class="container">
            <p>Daily Deals- Copyright &copy; 2011-1014 <span>Mr.Son</span> All rights reserved</p>
            <div class="payment pull-right">
                <img src="./public/img/footer/payment.png"/>
            </div>
        </div>
        <div class="back-to-top">
            <p class="fa fa-angle-up pull-right"></p>
        </div>
    </div>
</div>
