<div  id="header">
    <div class="container">
        <div class="menu-top">
            <ul class="form-group pull-left">
                <li>Support online:<a href="">(+84)978 135 793</a></li>
                <li class="language"><?php $this->Language(); ?></li>
                <li class="currency"><?php $this->Currency(); ?></li>
            </ul>
            <ul class="form-group pull-right">
                <li>Default wellcome msg!</li>
                <li><i class="glyphicon glyphicon-user">Accout</i><i class="fa fa-angle-down"></i></li>
            </ul>
        </div>
        <div class="logo"></div>
    </div>
    <div class="main-menu"></div>
</div>