<div id="header">
    <div class="container menu-top">
        <div class="form-group">
            <div class="phone">Support online:<a href="#">(+84)978 135 xxx</a></div>
            <div class="language">
                <img src="./public/img/header/language/england.png">
                <?php $this->Language(); ?>
                <i class="fa fa-angle-down"></i>
            </div>
            <div class="currency">
                <?php $this->Currency(); ?>
                <i class="fa fa-angle-down"></i>
            </div>
            <div class="pull-right form-group account">
                <p><a href="#">Default wellcome msg!</a></p>
                <div class="user">
                    <i class="glyphicon glyphicon-user"></i>
                    Accout
                    <i class="fa fa-angle-down"></i>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="logo-top">
    <div class="container">
        <div class="pull-left col-md-7 logo">
            <img class="img-responsive" src="./public/img/header/logo.png" alt="logo">
        </div>
        <div class="form-group pull-right col-md-3">
            <div class="fa fa-search search"></div>
            <div class="fa fa-shopping-cart cart"></div>
        </div>
    </div>
</div>
<div class="menu">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
            <ul class="nav navbar-nav">
                <li><a href="/admin">Home</a></li>
                <li><a href="./user">Travel</a></li>
                <li><a href="">Clothes</a></li>
                <li><a href="./blog/detail">Watch</a></li>
                <li><a href="<?php echo $baseurl.('admin');?>">Shoes</a></li>
                <li><a href="<?php echo $this->url.('admin');?>">Cell Phones</a></li>
                <li><a href="">Camera</a></li>
                <li><a href="">Computer</a></li>
                <li><a href="">Blog</a></li>
            </ul>
        </nav>
    </div>
</div>