<div id="header">
    <div class="container">
        <div class="menu-top">
            <ul class="form-group pull-left">
                <li>Support online:<a href="">(+84)978 135 793</a></li>
                <li class="language"><?php $this->Language(); ?></li>
                <li class="currency"><?php $this->Currency(); ?></li>
            </ul>
            <ul class="form-group pull-right">
                <li>Default wellcome msg!</li>
                <li>
                    <i class="glyphicon glyphicon-user">Accout</i>
                    <i class="fa fa-angle-down"></i>
                </li>
            </ul>
        </div>
        <div class="clearfix"></div>
        <div class="logo">
            <img class="img-responsive" src="./public/img/header/logo.png" alt="logo">
        </div>
        <div class="form-group pull-right">
            <div class="fa fa-search search"></div>
            <div class="fa fa-shopping-cart cart"></div>
        </div>
    </div>
    <div class="menu">
        <div class="container">
            <div class="navbar-header">
                <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
                <ul class="nav navbar-nav">
                    <li><a href="">Home</a></li>
                    <li><a href="">Travel</a></li>
                    <li><a href="">Clothes</a></li>
                    <li><a href="">Watch</a></li>
                    <li><a href="">Shoes</a></li>
                    <li><a href="">Cell Phones</a></li>
                    <li><a href="">Camera</a></li>
                    <li><a href="">Computer</a></li>
                    <li><a href="">Blog</a></li>
                </ul>
            </nav>
        </div>
    </div>
</div>