<?php echo $this->doctype() ?>
<html>
<head>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headScript() ?>
    <link href="./public/less/elements/footer.less" type="text/css" rel="stylesheet/less">

</head>
    <body>
        <?php
            echo $this->layout()->content;
        ?>
        <script src="./public/plugins/less/less.min.js" type="text/javascript"></script>
        <script src="./public/js/elements/footer.js" type="text/javascript"></script>
    </body>
</html>