<table width='300' align='center' border='1'>
    <tr>
        <td>User Id</td>
        <td>Username</td>
        <td>Level</td>
    </tr>
    <?php
    foreach($this->data as $item)
    {
        echo "<tr>";
        echo "<td align='center'>".$item['id']."</td>";
        echo "<td align='center'>".$item['username']."</td>";
        if($item['level'] == 1){
            echo "<td align='center'>Member</td>";
        }else{
            echo "<td align='center'><font color='red'>Admin</font></td>";
        }
        echo "</tr>";
    }
    ?>
</table>
<?php
echo $this->paginationControl($this->data, 'Sliding' , 'user/pagination.phtml');
?>
<?php echo $this->form; ?>

